WebApplication1/Models/Pizza.cs
using System.ComponentModel.DataAnnotations;
using Pizzeria.Attributes;

namespace Pizzeria.Models
{
    public class Pizza
    {
        public Pizza()
        {
            Ingredients = new List<Ingredient>();
        }

        public int Id { get; set; }

        [Required(ErrorMessage = "Please provide a pizza name.")]
        [StringLength(25)]
        public string Name { get; set; } = string.Empty;

		[Required(ErrorMessage = "Please provide a pizza price.")]
        [GreaterThanZero]
		public decimal Price { get; set; } = 0.0m;

		[Required(ErrorMessage = "Please provide a pizza description.")]
        [StringLength(255)]

		public string Description { get; set; } = string.Empty;
        [Required(ErrorMessage = "Please provide an image.")]
        public string Image { get; set; } = string.Empty;

        public int? CategoryId { get; set; }
        public Category? Category { get; set; }
        public List<Ingredient>? Ingredients { get; set;}
    }
}

WebApplication1/Controllers/PizzaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Pizzeria.Migrations;
using Pizzeria.Models;

namespace Pizzeria.Controllers
{
    public class PizzaController : Controller
    {
        public IActionResult Index()
        {
            using var _context = new PizzaContext();

            var data = _context.Pizzas.Include(p => p.Category).ToArray();

            return View(data);
        }

        public IActionResult Details(int id)
        {
            var _context = new PizzaContext();
            Pizza pizza = _context.Pizzas.Include(p => p.Category).Include(p => p.Ingredients).FirstOrDefault(p => p.Id == id);
            return View(pizza);
        }

        [Authorize(Roles = "ADMIN")]
        [HttpGet]
        public IActionResult Create()
        {
            using (PizzaContext _context = new PizzaContext())
            {
                PizzaFormModel model = new PizzaFormModel();
                List<Category> categories = _context.Categories.ToList();

                List<SelectListItem> listIngredients = new List<SelectListItem>();
                foreach(Ingredient ingredient in _context.Ingredients)
                {
                    listIngredients.Add(new SelectListItem()
                    { Text = ingredient.Name, Value = ingredient.Id.ToString() });
                }
                model.Ingredients = listIngredients;
                model.Pizza = new Pizza();
                model.Categories = categories;
                return View("Create", model);
            }
        }


        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create( PizzaFormModel data )
        {
			using PizzaContext _context = new PizzaContext();

            if (!ModelState.IsValid)
            {
                data.Categories = _context.Categories.ToList();
				return View("Create", data);
            }

            Pizza newPizza = new Pizza();
            newPizza = data.Pizza;

            if(data.SelectedIngredients != null)
            {
                foreach(string ingredientStrId in data.SelectedIngredients)
                {
                    int ingredientId = int.Parse(ingredientStrId);

                    Ingredient ingredient = _context.Ingredients.Where(i => i.Id == ingredientId).FirstOrDefault();
                    newPizza.Ingredients.Add(ingredient);
                
                }
            }
      
			_context.Pizzas.Add(newPizza);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "ADMIN")]
        [HttpGet]
        public IActionResult Update(int id)
        {
            using var _context = new PizzaContext();

            Pizza pizzaToEdit = _context.Pizzas.Where(pizza => pizza.Id == id).Include(p => p.Ingredients).FirstOrDefault();
            if (pizzaToEdit == null)
            {
                return NotFound();
            }

			List<SelectListItem> listIngredients = new List<SelectListItem>();
			foreach (Ingredient ingredient in _context.Ingredients)
			{
				listIngredients.Add(new SelectListItem()
				{ Text = ingredient.Name, Value = ingredient.Id.ToString(), Selected = pizzaToEdit.Ingredients.Any(i => i.Id == ingredient.Id)});
			}


			var formModel = new PizzaFormModel
            {
                Pizza = pizzaToEdit,
                Categories = _context.Categories.ToList(),
                Ingredients = listIngredients
            };

			return View(formModel);
        }

        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, PizzaFormModel data)
        {
            using var _context = new PizzaContext();

            if (!ModelState.IsValid)
            {
                data.Categories = _context.Categories.ToList();
                List<Ingredient> ingredients = _context.Ingredients.ToList();
                List<SelectListItem> listIngredients = new List<SelectListItem>();
                foreach(Ingredient ing in ingredients)
                {
                    listIngredients.Add(new SelectListItem() { Text = ing.Name, Value = ing.Id.ToString() });
                }
                data.Ingredients = listIngredients;
                data.Pizza.Id = id;

                return View("Update", data);
            }

            Pizza pizzaToEdit = _context.Pizzas.Where(pizza => pizza.Id == id).Include(p => p.Ingredients).FirstOrDefault();

            if(pizzaToEdit == null)
            {
                return NotFound();
            }

            pizzaToEdit.Name = data.Pizza.Name;
            pizzaToEdit.Price = data.Pizza.Price;
            pizzaToEdit.Description = data.Pizza.Description;
            pizzaToEdit.Image = data.Pizza.Image;

            pizzaToEdit.CategoryId = data.Pizza.CategoryId;
            pizzaToEdit.Ingredients.Clear();

            if(data.SelectedIngredients != null)
            {
                foreach(string ingStr in data.SelectedIngredients)
                {
                    int ingId = int.Parse(ingStr);
                    Ingredient ingredient = _context.Ingredients.Where(i => i.Id == ingId).FirstOrDefault();
                    pizzaToEdit.Ingredients.Add(ingredient);
                }
            }

            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "ADMIN")]
        public IActionResult Delete(int id)
        {
            using var _context = new PizzaContext();
            Pizza pizzaToDelete = _context.Pizzas.Where(p => p.Id == id).FirstOrDefault();
            if(pizzaToDelete == null)
            {
                return NotFound();
            }

            _context.Pizzas.Remove(pizzaToDelete);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        //API
        public IActionResult ApiIndex()
        {
            return View();
        }

        public IActionResult ApiCreate()
        {
            return View();
        }

        public IActionResult ApiUpdate(int id)
        {
            return View(id);
        }

        public IActionResult ApiDelete()
        {
            return View();
        }

    }
}

WebApplication1/Views/Pizza/ApiCreate.cshtml
<div class="container-lg mt-5">
	<form id="create-form" method="post" >

		@*name*@
		<div class="mb-3">
			<label class="col-form-label">Name</label>
			<input id="name-form" class="form-control" />
			<span class="text-danger"></span>
		</div>

		@*description*@
		<div class="mb-3">
			<label class="col-form-label">Description</label>
			<textarea id="description-form" class="form-control" placeholder="Put here pizza's description..'"></textarea>
			<span class="text-danger"></span>
		</div>
		<div class="row g-3">

			@*price*@
			<div class="col-4">
				<label class="form-label">Price</label>
				<input id="price-form" class="form-control">
				<span class="text-danger"></span>
			</div>

			@*category*@
			<div class="col-4">
				<label class="form-label">Category</label>
				<select id="category-form" class="form-select">
					<option selected value="">Choose...</option>

				</select>
				<span class="text-danger"></span>
			</div>

			@*ingredients*@
			<div class="col-4">
				<label class="form-label">Ingredienti</label>
				<select class="form-select">
					<option value="0">N/D</option>
				</select>
			</div>
		</div>

		@*image*@
		<div class="mb-3">
			<label class="col-form-label">Image</label>
			<input id="image-form" class="form-control" />
			<span class="text-danger"></span>
		</div>

		@*submit*@
		<button id="submit-form" type="submit" class="btn btn-dark">Create</button>
	</form>
</div>

@section Scripts{
	<script>
		initializeCreate()
	</script>
}

WebApplication1/Views/Pizza/ApiIndex.cshtml
<main class="pt-4">
    @if (User.IsInRole("ADMIN"))
    {
        <div class="mb-2">
            <a class="btn btn-success" href="@Url.Action("ApiCreate", "Pizza")"> Add pizza</a>
        </div>
    }

    <div class="input-group input-group-sm mb-3">
        <span class="input-group-text" id="inputGroup-sizing-sm">Filtra pizze</span>
        <input id="filter-bar" oninput="filtered()" type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
    </div>
    <div>
        @*pizza container*@
        <div id="table" class="d-flex justify-content-evenly flex-wrap">


        </div>
    </div>
</main>

@section Scripts{
    <script>
        initIndex("");
    </script>
}

WebApplication1/Views/Pizza/ApiUpdate.cshtml
@model int

<div class="container-lg mt-5">
	<form id="form" method="post">

		@*name*@
		<div class="mb-3">
			<label class="col-form-label">Name</label>
			<input id="name-form" class="form-control" />
			<span class="text-danger"></span>
		</div>

		@*description*@
		<div class="mb-3">
			<label class="col-form-label">Description</label>
			<textarea id="description-form" class="form-control" placeholder="Put here pizza's description..'"></textarea>
			<span class="text-danger"></span>
		</div>
		<div class="row g-3">

			@*price*@
			<div class="col-4">
				<label class="form-label">Price</label>
				<input id="price-form" class="form-control">
				<span class="text-danger"></span>
			</div>

			@*category*@
			<div class="col-4">
				<label class="form-label">Category</label>
				<select id="category-form" class="form-select">
					<option selected value="">Choose...</option>

				</select>
				<span class="text-danger"></span>
			</div>

			@*ingredients*@
			<div class="col-4">
				<label class="form-label">Ingredienti</label>
				<select class="form-select">
					<option value="0">N/D</option>
				</select>
			</div>
		</div>

		@*image*@
		<div class="mb-3">
			<label class="col-form-label">Image</label>
			<input id="image-form" class="form-control" />
			<span class="text-danger"></span>
		</div>

		@*submit*@
		<button id="submit-form" type="submit" class="btn btn-dark">Create</button>
	</form>
</div>





@section Scripts{
	<script>
		detailPizza(model)
	</script>
}

WebApplication1/Views/Pizza/Create.cshtml
@model PizzaFormModel
@{
    ViewData["Title"] = "create";
}

<div class="container-lg mt-5">
	<form method="post" asp-controller="Pizza" asp-action="Create">
		@Html.AntiForgeryToken()

		<div class="mb-3">
			<label asp-for="Pizza.Name" class="col-form-label">Name</label>
			<input asp-for="Pizza.Name" class="form-control"/>
			<span asp-validation-for="Pizza.Name" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Pizza.Description" class="col-form-label">Description</label>
			<textarea asp-for="Pizza.Description" class="form-control" placeholder="Put here pizza's description..'"></textarea>
			<span asp-validation-for="Pizza.Description" class="text-danger"></span>
		</div>
		<div class="row g-3">
			<div class="col-4">
				<label asp-for="Pizza.Price" class="form-label">Price</label>
				<input asp-for="Pizza.Price" class="form-control">
				<span asp-validation-for="Pizza.Price" class="text-danger"></span>
			</div>
			<div class="col-4">
				<label asp-for="Pizza.CategoryId" class="form-label">Category</label>
				<select asp-for="Pizza.CategoryId" class="form-select">
					<option selected value="">Choose...</option>
					@foreach(var category in Model.Categories)
					{
						<option value="@category.Id">@category.Name</option>
					}
				</select>
				<span asp-validation-for="Pizza.CategoryId" class="text-danger"></span>
			</div>
			<div class="col-4">
				<label asp-for="SelectedIngredients" class="form-label">Ingredienti</label>
				<div class="dropdown form-control">
					<button class="dropdown-toggle border-0 bg-transparent w-100" type="button" data-bs-toggle="dropdown" aria-expanded="false">
						Dropdown button
					</button>
					<ul class="dropdown-menu">
						<li>
							<select asp-for="SelectedIngredients"
									 multiple="multiple"
									 size="5"
									 class="form-control border-0"
									asp-items="@Model.Ingredients">
							</select>

						</li>
					</ul>
				</div>
			</div>
		</div>

		<div class="mb-3">
			<label asp-for="Pizza.Image" class="col-form-label">Image</label>
			<input asp-for="Pizza.Image" class="form-control" />
			<span asp-validation-for="Pizza.Image" class="text-danger"></span>
		</div>

		<button type="submit" class="btn btn-dark">Create</button>
	</form>
</div>

WebApplication1/Views/Pizza/Details.cshtml
@model Pizza
@{
    ViewData["Title"] = "details";
    var pizza = Model;
}

<div class="container">
    <h2 class="title">@pizza.Name</h2>
    <div class="flex-detail">
        <img src="/img/@pizza.Image" style="height:400px;">
        <div>
            <p><b>Descrizione: </b>@pizza.Description</p>
            <p><b>Prezzo: </b>@pizza.Price €</p>
            @if (pizza.Category != null)
            {
                <p><b>Categoria: </b>@pizza.Category.Name</p>
            }
            @if (pizza.Ingredients.Count() != 0)
            {
                <p>
                    <b>Ingredienti: </b>
                    @for (int i = 0; i < pizza.Ingredients.Count(); i++)
                    {
                        if(i < pizza.Ingredients.Count() - 1)
                        {
                            <text> @pizza.Ingredients[i].Name, </text>
                        }
                        else
                        {
                            <text> @pizza.Ingredients[i].Name. </text>
                        }
                    }
                </p>

            }

        </div>
    </div>

</div>

WebApplication1/Views/Pizza/Index.cshtml
@model Pizza[]

@{
    ViewData["Title"] = "Home Page";
    var pizzas = Model;
    using PizzaContext _context = new PizzaContext();
    Category[] categories = _context.Categories.ToArray();
    _context.Dispose();
}

            
<main class="pt-4">
    @if (User.IsInRole("ADMIN"))
    {
        <div class="mb-2">
            <a class="btn btn-success" href="@Url.Action("Create", "Pizza")"> Add pizza</a>
        </div>        
    }

    <div>
        @*pizza container*@
        <div class="d-flex justify-content-evenly flex-wrap">

            @*pizza cards*@
            @foreach(var pizza in pizzas)
            {
                <div class="card mb-5 bg-black bg-opacity-10" style="width: 18rem;">
                    <img src="@pizza.Image" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">@pizza.Name</h5>
                        <p class="card-text">@pizza.Description</p>
                    </div>
                    <div class="card-body">
                        @if(pizza.Category != null)
                        {
                            <p class="m-0"><b>Categoria: </b>@pizza.Category.Name </p>
                        }

                        <p class="m-0"><b>Prezzo: </b> @pizza.Price €</p>
                    </div>
                    <div class="card-body">
                        <a href="@Url.Action("Details", "Pizza", new {Id = pizza.Id})" class="btn btn-primary">Details</a>
                        @if (User.IsInRole("ADMIN"))
                        {                            
                            <a href="@Url.Action("Update", "Pizza", new {Id = pizza.Id})" class="btn btn-success">Update</a>
                            <form asp-controller="Pizza" asp-action="Delete" asp-route-id="@pizza.Id" method="post" class="btn btn-danger">
                                @Html.AntiForgeryToken()
                                <button type="submit" class="border-0 bg-transparent">
                                    Delete
                                </button>
                            </form>
                        }
                    </div>
                </div>
            }

        </div>
    </div>
</main>

WebApplication1/Views/Pizza/Update.cshtml
@model PizzaFormModel
@{
	ViewData["Title"] = "update";
	
}


<div class="container-lg mt-5">
	<form method="post" asp-controller="Pizza" asp-action="Update" asp-route-id="@Model.Pizza.Id">
		@Html.AntiForgeryToken()

		<div class="mb-3">
			<label asp-for="Pizza.Name" class="col-form-label">Name</label>
			<input asp-for="Pizza.Name" class="form-control" />
			<span asp-validation-for="Pizza.Name" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Pizza.Description" class="col-form-label">Description</label>
			<textarea asp-for="Pizza.Description" class="form-control" placeholder="Put here pizza's description..'"></textarea>
			<span asp-validation-for="Pizza.Description" class="text-danger"></span>
		</div>
		<div class="row g-3">
			<div class="col-4">
				<label asp-for="Pizza.Price" class="form-label">Price</label>
				<input asp-for="Pizza.Price" class="form-control">
				<span asp-validation-for="Pizza.Price" class="text-danger"></span>
			</div>
			<div class="col-4">
				<label for="inputState" class="form-label">State</label>
				<select asp-for="Pizza.CategoryId" class="form-select">
					<option selected value="">N/D</option>
					@foreach (var category in Model.Categories)
					{
						if(Model.Pizza.CategoryId == category.Id)
						{
							<option value="@category.Id" selected>@category.Name</option>
						}
						else
						{
							<option value="@category.Id">@category.Name</option>
						}
					}
				</select>
				<span asp-validation-for="Pizza.CategoryId" class="text-danger"></span>

			</div>
			<div class="col-4">
				<label asp-for="SelectedIngredients" class="form-label">Ingredienti</label>
				<div class="dropdown form-control">
					<button class="dropdown-toggle border-0 bg-transparent w-100" type="button" data-bs-toggle="dropdown" aria-expanded="false">
						Dropdown button
					</button>
					<ul class="dropdown-menu">
						<li>
							<select asp-for="SelectedIngredients"
									multiple="multiple"
									size="5"
									class="form-control border-0"
									asp-items="@Model.Ingredients">
							</select>

						</li>
					</ul>
				</div>
			</div>

		</div>

		<div class="mb-3">
			<label asp-for="Pizza.Image" class="col-form-label">Image</label>
			<input asp-for="Pizza.Image" class="form-control" />
			<span asp-validation-for="Pizza.Image" class="text-danger"></span>
		</div>

		<button type="submit" class="btn btn-dark">Update</button>
	</form>
</div>